name: sync-jd_scripts
on:
  workflow_dispatch:
  schedule:
    - cron: '1 */2 * * *'
jobs:
  sync:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    timeout-minutes: 2
    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential git git-core curl wget
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
    - name: Prepare Key
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.LXKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
    - name: Clone Master
      run: |
        git clone -b master git@gitee.com:lxk0301/jd_scripts.git master
    - name: Push Master
      uses: ad-m/github-push-action@master
      with:
        directory: master
        github_token: ${{ secrets.PAT }}
        branch: master
